# permissions for end users to view clustermaids.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clustermaid-viewer-role
rules:
- apiGroups:
  - webapp.cdx.foc
  resources:
  - clustermaids
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - webapp.cdx.foc
  resources:
  - clustermaids/status
  verbs:
  - get
