---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - webapp.cdx.foc
  resources:
  - clustermaids
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.cdx.foc
  resources:
  - clustermaids/finalizers
  verbs:
  - update
- apiGroups:
  - webapp.cdx.foc
  resources:
  - clustermaids/status
  verbs:
  - get
  - patch
  - update
